version: 2.1
executors:
  app-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}


jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache

  deploy-to-heroku:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - run:
          name: Deploy to Heroku
          command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]
          then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/cinema-app-prod.git ${CIRCLE_BRANCH}:master -f
          elif [ "${CIRCLE_BRANCH}" == "staging" ]
          then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/cinema-app-stage.git ${CIRCLE_BRANCH}:master -f
          else
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/cinema-app-develope.git ${CIRCLE_BRANCH}:master -f
          fi


workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-heroku:
          requires:
            -build
          filters:
            branches:
              only:
                - develop
                - staging
                - master

  